users=[
    {username="garyc@caseyandgary.com",subscription="garyc",filter=['garyc','bohu','family']},
    {username="caseych@caseyandgary.com",subscription="caseych",filter=['caseych','bohu','family']},
    {username="elise@caseyandgary.com",subscription="elise",filter=['elise','chubses']},
    {username="julian@caseyandgary.com",subscription="elise",filter=['julian','chubses']},
    {username="frank.chen@pioneerind.com",subscription="frank",filter=['frank','family']},
    {username="alice.chen@pioneerind.com",subscription="alice",filter=['alice','family']},
]
